# config/cable.yml

development:
  adapter: redis
  url: redis://ec2-3-223-100-250.compute-1.amazonaws.com:28860/0
  channel_prefix: my_app_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://ec2-3-223-100-250.compute-1.amazonaws.com:28860/0
  channel_prefix: my_app_production
