development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:pd1f21420561acf2c5d8b9247e1a12a102354d9a042a1c676cf938fb3124191a6@ec2-18-233-71-87.compute-1.amazonaws.com:27939
  # channel_prefix: Chatapp_production
